name: spellhelp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  tts: ^1.0.1
  flutter:
    sdk: flutter
  cloud_firestore: ^0.8.1 
  flutter_slidable: "^0.4.7"
  firebase_auth: ^0.5.20
  google_sign_in: ^3.0.4


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/mountains.jpeg
    - assets/images/mountains.jpg
  fonts:
      - family: icomoon
        fonts:
        - asset: assets/fonts/IcoMoon.ttf


dependency_overrides:
  tts: '1.0.1'


fonts:
  asset: fonts/SpellHelper.ttf
  